### ISSUE TITLE
Make it compatible with KeePass 2.43+

### ISSUE THREAD

**Issue by magneval** [dlech/KeeAgent#281] opened 2019-09-30 06:41 UTC
on this page https://lechnology.com/software/keeagent/ it is said «Not compatible with KeePass 2.43+» since September 11, 2019
I've upgrade to the latest KeePass, and I miss KeeAgent.

**Comment by dlech** [comment] 2019-09-30 13:27
Duplicate of #265

**Closed by dlech** 2019-09-30 13:27 UTC

**Comment by magneval** [comment] 2019-09-30 15:53
thank you

Le lun. 30 sept. 2019 à 15:27, David Lechner <notifications@github.com> a
écrit :
