### ISSUE TITLE
STRG+M entry in menus

### ISSUE THREAD

**Issue by Offerel** [dlech/KeeAgent#294] opened 2020-01-21 06:55 UTC
Installed KeePass 2.44 and KeeAgent 0.11.3.0. Since installation of KeeAgent i have empty entrys in "Group" and "Entry" menu if KeePass.
![screenshot_042](https://user-images.githubusercontent.com/14041522/72781833-8b30b080-3c22-11ea-85b3-690f60fc5f9b.jpg)
![screenshot_043](https://user-images.githubusercontent.com/14041522/72781839-8e2ba100-3c22-11ea-91e6-03eb930787b5.jpg)

KeePass chrashes, if i select the empty entry with:

```
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei KeeAgent.KeeAgentExt.PwEntryContextMenuLoadKeyItem_Clicked(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3468.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
KeePass
    Assembly-Version: 2.44.0.19625.
    Win32-Version: 2.44.0.0.
    CodeBase: file:///C:/Users/User/OneDrive/Tools/KeePass/KeePass.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3324.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3451.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3570.0 built by: NET472REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
KeeAgent
    Assembly-Version: 0.11.3.0.
    Win32-Version: 0.11.3.0.
    CodeBase: file:///C:/Users/User/AppData/Local/KeePass/PluginCache/cLzcZ1I15NIt5v3ds4Kb/KeeAgent.dll.
----------------------------------------
SshAgentLib
    Assembly-Version: 0.9.4.0.
    Win32-Version: 0.9.4.0.
    CodeBase: file:///C:/Users/User/AppData/Local/KeePass/PluginCache/cLzcZ1I15NIt5v3ds4Kb/SshAgentLib.DLL.
----------------------------------------
SshAgentLib.WinForms
    Assembly-Version: 0.9.2.0.
    Win32-Version: 0.9.2.0.
    CodeBase: file:///C:/Users/User/AppData/Local/KeePass/PluginCache/cLzcZ1I15NIt5v3ds4Kb/SshAgentLib.WinForms.DLL.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
KeeTrayTOTP
    Assembly-Version: 0.99.7325.11855.
    Win32-Version: 0.99.0.0.
    CodeBase: file:///C:/Users/User/AppData/Local/KeePass/PluginCache/f4X4ayCnf25FkGGPyT1U/KeeTrayTOTP.dll.
----------------------------------------
KeePass.XmlSerializers
    Assembly-Version: 2.44.0.19625.
    Win32-Version: 2.44.0.19625.
    CodeBase: file:///C:/Users/User/OneDrive/Tools/KeePass/KeePass.XmlSerializers.DLL.
----------------------------------------
System.Security
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2650.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
BouncyCastle.Crypto
    Assembly-Version: 1.8.1.0.
    Win32-Version: 1.8.1.146.
    CodeBase: file:///C:/Users/User/AppData/Local/KeePass/PluginCache/cLzcZ1I15NIt5v3ds4Kb/BouncyCastle.Crypto.DLL.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.
```

Could you please fix this?

**Comment by gusowski1** [comment] 2020-01-21 11:27
Duplicate of #283

**Closed** 2020-03-27 22:41 UTC
