### ISSUE TITLE
[Feature request] Support SHA512 key signing

### ISSUE THREAD

**Issue by ferenczy** [dlech/KeeAgent#285] opened 2019-11-06 19:09 UTC
I have upgraded a machine from _Debian 9_ to _Debian 10_ and now, when I'm connecting there using SSH, I'm getting the following warning:

    agent key RSA SHA256:[hash] returned incorrect signature type

As [I learned](https://superuser.com/questions/1499701/ssh-agent-key-rsa-sha256hash-returned-incorrect-signature-type), the issue is that the SHA1 hashing algorithm for key signing is not supported anymore, the SSH server and the SSH client negotiated the SHA512 algorithm to be used instead but KeeAgent returned the signature made using the SHA1 anyway.

Would it be possible to implement key signing using SHA512, please?

Currently, it's not critical, it doesn't have any impact on the ability to successfully connect but it may be causing issues in the future.

**Comment by dlech** [comment] 2022-05-24 16:00
Duplicate of #222.

**Closed by dlech** 2022-05-24 16:00 UTC
Labels: enhancement
