### ISSUE TITLE
KeeAgent fails to load under KeePass v2.43

### ISSUE THREAD

**Issue by knh1** [dlech/KeeAgent#268] opened 2019-09-11 03:52 UTC
Get the following error when KeePass tries to compile/load plugin on startup:

```
KeeAgent failed to load:

Insertion index was out of range. Must be non-negative and less than or equal to size.

Parameter name: index
```

Error occurs with both stable v0.10.1 and beta v0.11.0.

**Comment by dlech** [comment] 2019-09-11 03:58
Duplicate of #265

**Closed by dlech** 2019-09-11 03:58 UTC

**Comment by knh1** [comment] 2019-09-11 04:29
Sorry, should have looked closer.  Thanks for fixing so quickly!
