### ISSUE TITLE
Integration with bash on Windows 10 Preview

### ISSUE THREAD

**Issue by katekarnage** [dlech/KeeAgent#159] opened 2016-07-13 22:37 UTC
The good news is, this already works and should just need some documentation adding to tips and tricks.

Using the MSYSGIT socket functionality already provided, the bash/linux subsystem on windows 10 Preview can be made to use KeeAgent as it's ssh agent. 

I managed to do it using socat (apt-get install socat within bash on windows)  a script like the one below (pretty crude, ignores some things like proper host/network translation on the port number, because, well... the target architecture is known! and some cleanup could be added to .bash_logout etc) 

```
# If MSYSGIT socket in keeagent is set as c:\Users/foo/Documents/ssh_auth_msysgit
SSH_AUTH_KEEAGENT_SOCK=/mnt/c/Users/foo/Documents/ssh_auth_msysgit
SSH_AUTH_KEEAGENT_PORT=`sed -r 's/!<socket >([0-9]*\b).*/\1/' ${SSH_AUTH_KEEAGENT_SOCK}`

#use socket filename structure similar to ssh-agent
ssh_auth_tmpdir=`mktemp --tmpdir --directory keeagent-ssh.XXXXXXXXXX`
SSH_AUTH_SOCK="${ssh_auth_tmpdir}/agent.$$"

socat UNIX-LISTEN:${SSH_AUTH_SOCK},mode=0600,fork,shut-down TCP:127.0.0.1:${SSH_AUTH_KEEAGENT_PORT},connect-timeout=2 2>&1 > /dev/null &


```

**Comment by dlech** [comment] 2016-07-13 22:58
Nifty. I'll try this out when I get a chance.

**Comment by Kasceh** [comment] 2016-08-03 15:11
How do you go about using this to retrieve the SSH key? I've tried running this as a script and the last line doesn't appear to do anything? I've enabled MSYSGIT and pointed it at the same socket (`foo` swapped for my user name).

**Comment by mendhak** [comment] 2016-08-20 11:11
Thanks @katekarnage, never heard of `socat` until now.

I added this to my `~/.bashrc`, seems to work well with KeeAgent on launching Bash on Win10.

    #KeeAgent setup
    SSH_AUTH_KEEAGENT_SOCK=/mnt/c/Temp/syslockfile
    SSH_AUTH_KEEAGENT_PORT=`sed -r 's/!<socket >([0-9]*\b).*/\1/' ${SSH_AUTH_KEEAGENT_SOCK}`
    ssh_auth_tmpdir=`mktemp --tmpdir --directory keeagent-ssh.XXXXXXXXXX`
    export SSH_AUTH_SOCK="${ssh_auth_tmpdir}/agent.$$"
    socat UNIX-LISTEN:${SSH_AUTH_SOCK},mode=0600,fork,shut-down TCP:127.0.0.1:${SSH_AUTH_KEEAGENT_PORT},connect-timeout=2 2>&1 > /dev/null &

On connecting via SSH I do see this error though, is it something we can safely ignore? 

> 2016/08/20 12:08:46 socat[20] E write(4, 0xf24640, 5): Broken pipe

**Comment by dlech** [comment] 2016-10-02 23:27
It looks like unix sockets are at least partially implemented. https://github.com/Microsoft/BashOnWindows/issues/134

This is really what should be used here instead of socat.

**Comment by FlorinAsavoaie** [comment] 2016-11-15 21:24
Not extremely easy to implement the Unix sockets outside a WSL instance, as far as I can tell. Meanwhile I wrote this: https://gist.github.com/FlorinAsavoaie/8c2b6cb00f786c2caab65b1a51f4e847.

**Comment by h31** [comment] 2017-04-21 14:34
A major upgrade for Linux subsystem was released
https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/
Will it make things easier?

**Comment by rfnx** [comment] 2017-04-21 16:13
Still not working for me, even with the new Creators update.

I tried to declare the socket in KeeAgent options (both types, msysGit and Cygwin) and then export "SSH_AUTH_SOCK" in bash, but maybe I'm doing it wrong ?

**Comment by dlech** [comment] 2017-04-21 18:29
MSYS/Cygwin use TCP sockets, not Unix sockets, so they will not work with native Linux ssh programs. We need to figure out how to create a Unix socket from a Windows program (if that is even possible) or perhaps automate the `socat` tunnel that is described in the opening comment here.

**Comment by saxonww** [comment] 2017-04-21 18:57
https://github.com/ionescu007/lxss might help answer this question.

I've spent less than 5 minutes looking at this, but it suggests that there is an 'ADSS bus' which is the bridge between the Win32 and WSL environments. It might not really be possible (yet) to just create a socket file from a Win32 program and have it be recognized as such by a WSL process; there would maybe need to be something like the lxext/lxexec method described in the readme for this repo.

**Comment by saxonww** [comment] 2017-04-21 18:59
Also fwiw I have been using a modified version of @FlorinAsavoaie's python thing for several months. It works as well or better than the socat method, with the one downside being if I try to close my WSL window(s) while keepass is locked, I get into a db unlock loop that is really hard to get out of.

**Comment by h31** [comment] 2017-04-21 19:15
> https://github.com/ionescu007/lxss might help answer this question.
WSL from Creators update allows to run arbitrary Linux command from the Windows executable. There's no need to use unofficial tools.

**Comment by saxonww** [comment] 2017-04-21 21:02
Does this new capability extend to reading and writing from an Linux socket file?

**Comment by h31** [comment] 2017-04-21 22:14
Haven't heard about such possibilities. I've posted a link above, maybe it will help.

**Comment by strarsis** [comment] 2017-09-15 13:56
I use this now in .bashrc:
````
# KeeAgent
export SSH_AUTH_SOCK="/tmp/.ssh-auth-sock"
~/bin/msysgit2unix-socket.py /mnt/d/pass/keeagent-msysgit:$SSH_AUTH_SOCK
````

It uses the msysgit2unix-socket python script, a recent fork you can find here:
https://gist.github.com/duebbert/4298b5f4eb7cc064b09e9d865dd490c9

**Comment by saxonww** [comment] 2017-12-19 23:10
https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/ !!

**Comment by strarsis** [comment] 2018-01-14 22:31
Currently working howto: https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

**Comment by strarsis** [comment] 2018-02-26 02:12
What is cool is that it also works with FileZilla Normal login and some other SSH clients on Windows.
They seem to share the same library.

**Comment by pscheit** [comment] 2018-08-01 09:27
if [ ! -f /tmp/ssh-agent-pipe ]; then
  sudo socat UNIX-LISTEN:/tmp/ssh-agent-pipe,fork,group=yourusernamegroup,umask=007 EXEC:"npiperelay.exe -ep -s //./pipe/openssh-ssh-agent",nofork &
fi

and enable the experimental open ssh support 
https://github.com/jstarks/npiperelay

after reading this thread i should've known, that there is already a tcp socket available to bind with socat, but leaving this here for someone who's interested ..

**Comment by strarsis** [comment] 2018-08-01 11:30
@pscheit: Where do I have to enable the experimental open ssh support? Is this a npiperelay option or a KeeAgent option?

**Comment by pscheit** [comment] 2018-08-01 12:00
![image](https://user-images.githubusercontent.com/488189/43520460-410b5618-9593-11e8-91ba-20bb0eb28295.png)

jip

**Comment by strarsis** [comment] 2018-08-01 13:52
@pscheit: How can I avoid sudo prompt at the beginning of each shell session?
Besides this issue, typing in terminal becomes strange sometimes.
When using Ctrl+C in shell, the command exits with code 130.

**Comment by reynoldsbd** [comment] 2019-01-14 01:33
Hello! I am not a KeeAgent user, but I got a tip that folks here might be interested in [wsl-agent-bridge](https://github.com/reynoldsbd/wsl-agent-bridge). In short, it allows WSL to transparently use the Windows port of ssh-agent [via an AF_UNIX socket](https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/).

**Comment by BWibo** [comment] 2019-03-07 10:13
This works fine for me.
[https://solariz.de/de/ubuntu-subsystem-windows-keepass-keeagent-pageant-linux-ssh.htm](https://solariz.de/de/ubuntu-subsystem-windows-keepass-keeagent-pageant-linux-ssh.htm)
It uses [weasel-pagent](https://github.com/vuori/weasel-pageant).

```
Win10 x64, Version 1803, Build 17134.590

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
```

**Comment by r2evans** [comment] 2020-05-30 18:07
@BWibo, I found the link you provided to be stale, I think the updated links are [de](https://tcpip.wtf/de/ubuntu-subsystem-windows-und-keepass-keeagent-pageant-.htm)
and [en](https://tcpip.wtf/en/linux-ubuntu-subsystem-windows-keepass-keeagent-pageant.htm) (the "de" version says that the "en" page is an updated version, not sure, I don't know German and have not otherwise translated the page).

Regardless, though, it appears that `weasel-pageant` is self-deprecated (and now past end-of-life). Some preferences include [WinCryptSSHAgent](https://github.com/buptczq/WinCryptSSHAgent) or [wsl-ssh-pageant](https://github.com/benpye/wsl-ssh-pageant), though I think only the latter might be compatible with KeeAgent.

It's been a year since you provided that script. Are you still using these methods? Have you shifted to something else? I've just updated to wsl2, and I'm trying to determine my options for having a unified windows/GfW/wsl2 ssh experience. Thanks!

**Comment by BWibo** [comment] 2020-06-09 14:23
Hey there, I can confirm this working with Ubuntu 20 on WSL 1. However, I have had some issues every now and then, but it works in general.

This link works and contains some updates as well:
https://tcpip.wtf/en/linux-ubuntu-subsystem-windows-keepass-keeagent-pageant.htm

This is what I currently use:

``` bash
#!/usr/bin/env zsh
# see: https://tcpip.wtf/en/linux-ubuntu-subsystem-windows-keepass-keeagent-pageant.htm

# config
WEASELPAGEANTVERSION=1.4
WEASELPAGEANTDIR="$HOME/.weasel-pageant/weasel-pageant-$WEASELPAGEANTVERSION"

echo "WeaselPAgeant v$WEASELPAGEANTVERSION"

# run weasel-pagent
echo -n "pageant:"
eval $("$WEASELPAGEANTDIR/weasel-pageant" -r -b -a "$HOME/.wslsock")

sleep .1
sshkeysloaded=$(ssh-add -l|grep -c RSA)
if [[ $sshkeysloaded -gt 0 ]] ; then
    echo -e "\e[92m OK, ready for Agent forward, loaded $sshkeysloaded keys."
 else
    echo -e "\e[91m Fail, no keys found or pageant connection failed. "
fi
echo

```

**Comment by musm** [comment] 2020-06-13 18:07
So how can I use KeeAgent within WSL2 ? There's a lot of conflicting results/methods. Thanks

**Comment by r2evans** [comment] 2020-06-13 21:50
I haven't found a working solution yet. I suspect I'm mis-using `socat` and/or `npiperelay`, so I don't know if it's a problem with WSL2 or with my attempts.

**Comment by BWibo** [comment] 2020-06-16 09:34
One of the reasons I haven't switched to WSL2 is that there is no working KeeAgent integration jet...

**Comment by strarsis** [comment] 2020-06-16 09:47
Thanks for the information! I use KeePass + KeeAgent intensively and having issues on WSL 2 would be a blocker, hence I will wait with migration to WSL 2.

**Comment by strarsis** [comment] 2020-06-20 12:22
Thanks to the instructions for WSL 2 of the `wsl-ssh-agent` project it works now: https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility

**Comment by musm** [comment] 2020-06-21 06:03
> Thanks to the instructions for WSL 2 of the `wsl-ssh-agent` project it works now: https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility

Wow awesome ! Tested and totally works. Just at tip for others trying to make it work on WSL 2 using this guide. Extract npiperelay from `https://github.com/rupor-github/wsl-ssh-agent#wsl-2-compatibility`  to a Windows path, e.g.: `C:\Tmp\npiperelay.exe` then modify the text there and set in your bashrc file 
```
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0   ]; then
    rm -f $SSH_AUTH_SOCK
    ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"/mnt/c/Tmp/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork & ) >/dev/null 2>&1
fi
```

In the original guide it says to extract `npiperelay.exe` to `$HOME/winhome/.wsl/npiperelay.exe` but that didin't work

**Comment by strarsis** [comment] 2020-09-05 21:08
Howto: https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

**Comment by leonard84** [comment] 2020-09-23 15:19
@BWibo  just for completeness sake, weasel-pagent works just fine with WSL 2. It is still deprecated, but so far it is IMHO the easiest solution until keeagent somehow gets direct WSL(2) support.

**Comment by strarsis** [comment] 2020-09-23 15:23
@leonard84: Not trying to be bragging here, but you should check out this HOWTO: Howto: https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49
👍

**Comment by dlech** [comment] 2022-01-29 22:50
I've just merged a change to allow KeeAgent to work directly with WSL1 and opened a new issue to document the WSL2 workaround (#339).

**Closed by dlech** 2022-01-29 22:50 UTC
Labels: enhancement, docs needed
