### ISSUE TITLE
1.13.7 crashes (on Linux)

### ISSUE THREAD

**Issue by a-m-s** [dlech/KeeAgent#412] opened 2024-05-13 13:07 UTC
1.13.6 works fine, but Keepass fails to start when I install 1.13.7. Downgrading fixes the issue.

There's a long dump message, but I think this is the interesting part:
```
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
mono: ../../src/xcb_io.c:833: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
```

**Comment by dlech** [comment] 2024-05-13 14:04
Duplicate of #410

**Closed by dlech** 2024-05-13 14:04 UTC
Labels: duplicate
