### ISSUE TITLE
Plugin incompatible error

### ISSUE THREAD

**Issue by CruzMarcio** [dlech/KeeAgent#350] opened 2022-07-27 12:47 UTC
Hi, I`m getting this error after upgrading to KeeAgent 0.13.1, using KeePass 2.51.1.

[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\KeePass\Plugins\KeeAgent.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
ResX file Type System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a cannot be located. Line 123, position 5. cannot be parsed.
System.Windows.Forms
   at System.Resources.ResXResourceReader.ParseXml(XmlTextReader reader)
   at System.Resources.ResXResourceReader.EnsureResData()
   at System.Resources.ResXResourceReader.GetEnumerator()
   at KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void ParseXml(System.Xml.XmlTextReader)

Inner:
Type System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a cannot be located. Line 123, position 5.

[^] Details  [OK]

**Comment by dlech** [comment] 2022-07-27 14:27
Duplicate of #16 and #111? Unfortunately those users were not able to give a fix, but it points to a problem with the .NET Framework rather than a problem with KeeAgent.

**Comment by CruzMarcio** [comment] 2022-07-27 19:37
Any suggestion on what I can try? This happens with 2 different systems I have, both running Windows 11. One is my personal computer and the other is my work computer.

**Comment by dlech** [comment] 2023-02-04 18:45
Generally this is caused by KeePass running using an older .NET version. This can be managed by editing the `KeePass.exe.config` file.

**Closed by dlech** 2023-02-04 18:45 UTC
