### ISSUE TITLE
KeeAgent failed to load on KeePass 2.43

### ISSUE THREAD

**Issue by joaociocca** [dlech/KeeAgent#275] opened 2019-09-16 14:32 UTC
After updating to KeePass 2.43, whenever I open it I get this error:
"O índice de inserção estava fora do intervalo. Ele deve ser não-negativo e menor ou igual ao tamanho.
Nome do parâmetro: index"

or in English...

"The insertion index was out of range. It must be non-negative and less than or equal to size.
Parameter Name: index"

After OK'ing the error popup, nothing shows on the Plugin window in Tools. KeeAgent is, effectively, disabled.

**Comment by dlech** [comment] 2019-09-16 14:40
Duplicate of #265

**Closed by dlech** 2019-09-16 14:40 UTC
