### ISSUE TITLE
problems with new RFC4716 key format?

### ISSUE THREAD

**Issue by creidhne-a16i** [dlech/KeeAgent#251] opened 2018-11-29 19:16 UTC
ED25519 keys generated using git bash `ssh-keygen -t ed25519 -o -a 100 -P random-30-characters -C ed25519-key-20181129` added to database start causing keepass to have a very noticeable few second lag for everything. It becomes especially noticeable with 3 or more keys saved as attachments in said databse - they become a problem even when they are not loaded, but the column "SSH Key Status" is enabled and the group with SSH keys is viewed. With keys unloaded and "SSH Key Status" column disabled, the only lag that is left is when the database is being opened or closed.

ED25519 keys generated using puttygen work without issues and do not generate any lag when used to replace "laggy" keys in the same database - everything works instantly. Tested across two different machines, one AMD and one Intel. KeePass v2.40, Keeagent v0.10.1.
I suspect this has something to do with ssh-keygen -o option I used that enables usage of the new RFC4716 key format?

**Comment by dlech** [comment] 2019-03-08 21:34
Duplicate of #243?

**Closed** 2022-05-07 19:06 UTC
