### ISSUE TITLE
help track down repeated key requests

### ISSUE THREAD

**Issue by r2evans** [dlech/KeeAgent#93] opened 2014-12-18 20:44 UTC
I'm running KeePass 2.28 with KeeAgent 0.5.4 beta (and KeePassRPC 1.4.4.0, if it contributes). I'm using the ssh-agent portion (cygwin-mode for msys2), and it works great. I have "Show a notification balloon" selected, no problems. I have "Always require manual confirmation" disabled. It works great for my uses of ssh and git (which uses ssh); I have nothing else configured to use `.ssh-agent`. (Thanks!)

Occasionally (twice in the last week), though, I get repeated balloons with no ssh use on my part. I do not have any automated scripts or git push/pull requests going. I use emacs, but I have not configured it to auto-pull/push anything via vc/git, and I have never used it for direct ssh work.

I have a couple of suspicions, with various levels of confidence and in no particular order:

1) KeePass/KeeAgent is misbehaving.
2) KeeAgent/KeePassRPC interaction (I don't think this is likely, but I don't know enough about their respective implementations).
3) Some windows function is doing a filesystem scan and, merely by probing the `.ssh-agent` file, it prompts KeeAgent to show the balloon. **Does KeeAgent show the balloon on each attempt to get a key, regardless if it is a well-formatted request?** This is not happening during scheduled anti-virus scans.
4) Virus/malware/... I'm generally good about phishing and such, and my anti-virus is up-to-date (though that's no guarantee).

When the balloons start appearing (with about 5 seconds break, repeated many times), I cannot immediately see an aberrant process, but they can start and exit faster than the typical task manager list can update, so that's no guarantee.

I'll play around with enabled "Always require manual confirmation," perhaps that will provide some insight.

What else can I do to try to narrow down what process is responsible for these key requests?

BTW: win7_64. I typically have several apps open: chrome, emacs, excel, firefox, msys2/mintty, and thunderbird. Both FF and TB use KeeFox for KeePassRPC.

**Comment by r2evans** [comment] 2015-01-09 17:44
It's been a few weeks, so I thought I'd update the thread.

After I enabled "Always Confirm", I have not seen any more runaway connection requests. I will deselect it at some point to see if I can again trigger the event. I can't imagine that this condition alone would enable/prevent the event, so I'm guessing that it was a runaway process that I was not able to track down.

Feel free to close this Issue discussion (or leave it open, over to you); if I see the problem pop up again, I'll try to bring more information.

Thanks, Dave.

**Comment by dlech** [comment] 2015-01-09 19:03
Thanks for the follow up. Since you can't reproduce the problem, I am going to close the issue. But if it ever does pop up again, just reopen it.

**Closed by dlech** 2015-01-09 19:03 UTC
