### ISSUE TITLE
Pageant - Dev Snapshot 2016-07-19.9398d23

### ISSUE THREAD

**Issue by mkosmo** [dlech/KeeAgent#168] opened 2016-09-01 15:28 UTC
Howdy,

When trying to run KeeAgent in Client mode and a dev snapshot of Pagent, I get the following error:
![keeagenterror](https://cloud.githubusercontent.com/assets/115102/18173118/0279588c-702e-11e6-9acf-b75d719bf61a.png)

KeePass 2.34
KeeAgent 0.8.1.0
Pageant Dev Snapshot 2016-07-19.9398d23 (for ECDSA/ed25519 support)

It does, however, work with the Pageant 0.67 beta (other versions remaining the same), but I'm missing out on ECDSA/ed25519 support.

**Comment by dlech** [comment] 2016-10-02 23:20
I am not able to reproduce this problem with `Development snapshot 2016-09-20.24da181`, so either this has been fixed in Pageant or you will need to attach a key that causes this error that I can use for testing.

**Comment by dlech** [comment] 2017-03-02 01:34
Please re-open the issue if this is still a problem.

**Closed by dlech** 2017-03-02 01:34 UTC
