### ISSUE TITLE
Error with Keeagent after Installation Keepass 2.43

### ISSUE THREAD

**Issue by atsirk** [dlech/KeeAgent#280] opened 2019-09-27 07:36 UTC
![keepassagent](https://user-images.githubusercontent.com/3855109/65751172-3cf32100-e10a-11e9-9df1-3ca84ebbd55f.jpg)

**Comment by dlech** [comment] 2019-09-27 13:31
Duplicate of #265

**Closed by dlech** 2019-09-27 13:31 UTC
