### ISSUE TITLE
Socket File not deleted on Windows Shutdown

### ISSUE THREAD

**Issue by infomaniac50** [dlech/KeeAgent#92] opened 2014-12-10 18:43 UTC
I'm having a problem with the beta version 0.5.4. The socket file isn't getting deleted when keepass exits because of a shutdown or restart event. When the system comes back up keeagent prompts me with a dialog saying the file already exists. If I exit keepass manually before doing a restart/shutdown then the file is deleted and everything is fine.

It took me a while to figure out the file wasn't being deleted on shutdown. The socket file is located in my user profile directory/home folder.

I have tried both socket types Cygwin and MSYS and both exhibit the same behavior 

## Specs ##
Windows 8.1
It's probably not relevant but Intel's 3rd gen Ivy Bridge processor has AES-NI
AES-NI helps with KeePass database encryption and among other things TrueCrypt.
16GB RAM
Not the fastest HDD in the world
Seagate ST95005620AS (For a while I suspected it might be an iowait issue with so much going on at login. Autostart, services, etc.)

### Environment ###
socket file is in my User Profile directory ``C:\Users\Derek\.ssh-agent``
I also have an environment variable set on my user profile.
``SSH_AUTH_SOCK = C:\Users\Derek\.ssh-agent``
I used to run the stable version of this plugin in client mode with Pageant. The beta version makes Pageant irrelevant.

**Comment by dlech** [comment] 2015-02-15 04:11
I was not able to reproduce this on Windows 8.1 in a virtual machine. I will need more information on how to reproduce this in order to fix this bug.

I have just done a stable release (v0.6.0). I did make one small change since the last beta that *might* fix this, so give it a try.

**Comment by mkresin** [comment] 2015-03-06 08:38
Confirming this issue with Windows 7 Professional in a domain enviroment, KeePass 2.28, KeeAgent v0.6.0 and a Cygwin socketfile. I'm unsure if it happens all the time, but at I had this issue two times this week.

**Comment by mkresin** [comment] 2015-03-06 08:49
Missed to mention, that I normally get the "Waiting for background programs to close" screen when shutting down the system.

![Waiting for background programs to close](http://www.geekzone.co.nz/imagessubs/blogbbbc297eca292c3568881967ee370d0a.jpg)

This isn't related to KeePass/KeeAgent, but could be the key to reproduce the issue. I suspected the used antivirus solution is the cause for this screen. I haven't debugged this any further, since it disappears relatively fast by itself and the shutdown continues.

**Comment by mkresin** [comment] 2015-06-03 09:47
I can reliable reproduce the issue if I use the taskmanager or ```taskkill /F /IM "keepass.exe"``` to kill the KeePass process. I guess something similar happens if the "Waiting for background programs to close" screen appears.

According to http://serverfault.com/a/151788 the ```WM_CLOSE```  message is posted to the program's windows on kill or hitting the X button. Dunno if ```WM_CLOSE``` is send as well, if the the Option "Close button [X] minimizes main window..." is enabled.

\<wild guessing\>
Maybe the close signal isn't passed to keepass plugins or keeagent doesn't take care of the signal?
\<\/wild guessing\>

**Comment by dlech** [comment] 2015-06-03 16:36
The serverfault answer also says:

> If the program does not exit in some time, user gets prompted to end the program forcefully.

It sounds like this is what is happening during shutdown. KeePass does not close fast enough because the system is busy doing other things and if forcefully terminated.

By running `taskkill /F`, you are *forcefully* shutting down the program. The process is ended immediately, so there is no chance that any more code could run and remove the files.

I'm afraid the only solution here is to get in the habit of closing KeePass manually before your restart or shutdown.

**Comment by dlech** [comment] 2015-06-03 16:37
Unless maybe you have KeePass configured so that the close button minimizes to tray instead of closing KeePass.

**Comment by infomaniac50** [comment] 2015-06-03 16:55
I can confirm that WM_CLOSE is sent to application windows even if the close to tray option is checked. Win32 applications "handle" these messages sent from the Windows desktop subsystem. There are defaults in .NET but Win32 apps can choose to ignore these messages. You can create a perfectly legit program where the window action buttons do nothing. I don't think .Net exposes an API to handle these messages on such a low-level but this would make sense. Forcefully closing an application is probably the equivalent of SIGKILL on Linux. If the application is not responding it is halted and it's virtual address space is unloaded. As with Linux forcefully closing an application does not give the program a chance to clean up.

The only other way I can think of is to use an extra option that allows overwriting the file on startup. For my workspace the only thing that touches the file is KeeAgent so this would be my preferred method since I can already choose where to place the file.

I have been mostly a Windows guy but lately I've been dual booting Ubuntu for work. Windows hit a deadend with Linux-y development because of basic filesystem limitations. Windows does not get out much anymore and is also the reason I have not been active on this issue lately.

[Explaination of Linux Signals TERM vs KILL](https://major.io/2010/03/18/sigterm-vs-sigkill/)

**Comment by dlech** [comment] 2015-06-03 17:13
> The only other way I can think of is to use an extra option that allows overwriting the file on startup.

I might consider doing this. This is a problem though if you start two instances of KeePass at once. The second one will overwrite the first. Of course, anyone using KeeAgent won't have 2 instances of KeePass open most likely.

**Comment by mkresin** [comment] 2015-06-03 17:39
> By running taskkill /F, you are forcefully shutting down the program

My bad. Didn't took care of the last paragraph of the answer and I had the incorrect impression that the taskmanager end tasks (ExitProcess()) instead of killing (TerminateProcess()) them. 

> This is a problem though if you start two instances of KeePass at once.

What about making the setting depended on the "Limit to single instance" setting of Keepass?

**Comment by infomaniac50** [comment] 2015-06-03 19:14
To me, forcefully means Windows is not going to be nice about it but it also raises another question. The shutdown prompt that shows stalled background applications has a force close button. The application usually exits before the user takes action though. This would imply the system was just highly loaded and the application was unable to exit in a timely manner but eventually did so successfully.

The WM_CLOSE feels separate somehow. I remember vaguely that WM_CLOSE was not used everywhere. It's just a hunch but a Windows shutdown may initiate a different code path for running applications. WM_CLOSE is really just for GUI applications.

I just remembered that all messages are passed to a callback function called HandleMessage. So yeah the application doesn't have to do anything with them as long as it returns a code indicating it handled the message. It let's the application know that the user did something outside of the applications scope and if one even exists, it executes the appropriate callback function. WM_CLOSE may not even be called if the application is in the tray since a handle to the application window does not exist. Each form in Windows is really just another handle that it sends messages to. It just depends on which form handles the message first. If it is not handled it bubbles up to the parent handle.

If we can find it, there might be a callback for ProcessExit which goes for CUI and GUI alike. Adding a handler to the current processes exit event might work. It depends on how the plugins are segregated in KeePass. You might have to add a handler for the AppDomain or Thread instead of the process.

I don't think I have ever had two instances of KeePass open. I don't know what the benefit would be since you can open multiple databases in one instance. They show up as tabs in the toolbar menu. Of course simply opening KeePass may do damage if there are no checks in place but making the options mutually exclusive might cause one instance that doesn't use KeeAgent prevent the next one that does complain about it. The user might prefer the second instance over the first if it is not used.

KeePass A - KeeAgent not used
KeePass B - KeeAgent used but socket file exists from A so we can't do anything.

I know I have pushed one too many buttons by accident but I take corrective action on my own if it becomes a persistent problem.

I'm not sure how KeePass exposes the settings through it's API. If they are all fetched at once into an object we could go ahead and say, "Hey the single instance setting is not checked. Opening another instance could corrupt your current socket file." Then the behavior is dependent on the user's preference.

Another thing I'm not sure on is where KeeAgent settings are stored for this. Are the settings for the socket global to the application instance or are the stored within the database settings. If they are stored in the database you can set the location for the socket file for each database so they don't conflict.

**Comment by dlech** [comment] 2015-06-03 20:16
> HandleMessage may not even be called if the application is in the tray since a handle to the application window does not exist.

That's an interesting point. Do either of you know if this issue only happens when KeePass is minimized to tray (nothing in the taskbar).

**Comment by kgraefe** [comment] 2015-06-10 09:50
I can say that I run into this bug occasionally and that I have KeePass minimized to tray almost always.

(I can't say whether the bug occurs when KeePass is not minimized to tray.)

**Comment by infomaniac50** [comment] 2015-06-14 22:20
I may have discovered why this issue is so intermittent. While testing with KeePass 2.29 I noticed I could not reproduce the problem. A few months back I upgraded to 2.29 from 2.28 and I wondered if it could be a KeePass thing. I downgraded KeePass to 2.28 and sure enough the .ssh-agent file was there after a reboot. The new version was released some time in April and it's probably the reason why dlech could not reproduce the problem either.

#### Testing Procedure ####
 1. Open 1 kdbx database.
 - Minimize the appliation to the tray
 - Restart the computer with the Alt-F4 shutdown prompt.
 - Login and open the directory where your .ssh-agent file resides.
 - Note if the .ssh-agent file exists

I did this for both KeePass 2.29 and KeePass 2.28 in that order.
After downgrading KeePass and restarting the computer the .ssh-agent file still exists!

I did not test it with KeePass in the taskbar (**Not** minimized to the tray).
I will upgrade KeePass 2.29 and try to make it fail again.

**Comment by infomaniac50** [comment] 2015-06-14 22:48
It seems to fail randomly. I have installed both versions multiple times and tested over multiple reboots. For whatever reason it seems to fail about 1 out of every 10 tries. After one install I noticed the plugin cache didn't update but whether this has any impact on plugin functionality is unknown. Right now I'm highly suspicious of Windows' virtual address space management. Non-deterministic behavior in a program indicates interference from the operating system. It's behavior will be defined by the kernel and all other programs running on the system.

**Comment by kgraefe** [comment] 2015-06-30 10:39
Could KeeAgent at least work around the issue by either removing the file automatically (maybe there is a way to check if another instance is running on the socket?) or by asking the user whether to remove the file or not?

Currently I always have to click `OK` on the error message, close KeePass, remove the file and restart KeePass again...

**Comment by dlech** [comment] 2015-07-01 01:35
Sorry I haven't had a chance to work on this yet.

> maybe there is a way to check if another instance is running on the socket?

Yes, thanks to some yet unreleased changes from #59, there is now code in place to do this. Now that this is possible, I think we can do this and also check the contents of the file to make sure it looks like a socket file. Then we can safely delete an existing file without user intervention.

In the mean time, you can continue to manually delete the file, but instead of restarting KeePass, you can open the Tools > Options dialog in KeePass and click 'OK'. This should recreate the socket file. At least you don't have to type your password in again that way.

**Comment by dlech** [comment] 2015-07-10 04:02
OK, I've added a feature to write over socket files if they exist when KeePass starts up. Let me know how it works for you.

http://lechnology.com/2015/07/keeagent-beta-v0-7-2-released/

**Comment by kgraefe** [comment] 2015-07-20 22:24
Sorry for the delay. I can confirm that v0.7.2 solves the issue when I kill KeePass through the task manager. Thank you.

I will use v0.7.2 for production now. and report will report when the issue raises again. But since the issue itself is relatively seldom, we will never know for sure. :D

**Comment by dlech** [comment] 2015-07-20 22:32
Great! I'm going to call this closed for now (unless someone says otherwise).

**Closed by dlech** 2015-07-20 22:32 UTC
Labels: enhancement
