### ISSUE TITLE
v0.11.1 doesn't work on Ubuntu 16.04.6

### ISSUE THREAD

**Issue by RoSk0** [dlech/KeeAgent#277] opened 2019-09-18 02:10 UTC
![KeePass_015](https://user-images.githubusercontent.com/119257/65101979-d4c38180-da1d-11e9-9813-7aba727d8367.png)

KeePass: 2.43
```
$ aptitude show mono-runtime
Package: mono-runtime                    
State: installed
Automatically installed: yes
Version: 4.2.1.102+dfsg2-7ubuntu4

```

**Comment by dlech** [comment] 2019-09-18 02:17
Duplicate of #271

**Closed by dlech** 2019-09-18 02:17 UTC
