### ISSUE TITLE
Enabling Keeagent on Ubuntu now needs an extra step

### ISSUE THREAD

**Issue by rojaro** [dlech/KeeAgent#89] opened 2014-11-17 10:56 UTC
With current version of Ubuntu, changing the .desktop file mentioned in the documentation is not sufficient anymore. An additional upstart job was added that also starts gnome-keyring-daemon. The file is located in /usr/share/upstart/sessions/gnome-keyring.conf and contains:

```
eval "$(gnome-keyring-daemon --start)" >/dev/null
initctl set-env --global SSH_AUTH_SOCK=$SSH_AUTH_SOCK
initctl set-env --global GPG_AGENT_INFO=$GPG_AGENT_INFO
```

Here the daemon needs to be restricted to only provide some services by adding --components=pkcs11,secrets to the command line. The initctl lines can also be removed, resulting in:

```
eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets)" >/dev/null
```

**Comment by taurus-forever** [comment] 2015-01-19 08:58
JFYI (for other users): I have noticed a strange problem on newly installed Ubuntu 14.04. 
KeePass(2.28)/KeeAgent(0.4.1-3) perfectly loads keys first time after reboot, but failed to load them next time(s) if KeePass has been locked/restarted. Full system reboot helps only for me. Error says: "Cannot connect to socket ...".

The problem disappears after downgrading gnome-keyring from "3.10.1-1ubuntu4.1" to "3.10.1-1ubuntu4" (P.S. do not forget to put the package on hold: "sudo apt-mark hold gnome-keyring").

IMHO, it is good to add this info here: http://lechnology.com/software/keeagent/installation/#disable-ssh-component-of-gnome-keyring

Also, Ubuntu bugreport has been closed: https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1271591 . So I am not sure how lown we will be able to workaround this.

**Comment by dlech** [comment] 2015-01-20 03:00
FWIW, I opened a [new bug on launchpad](https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1412624).

I've gone ahead and updated the docs. Thanks for the tip on `apt-mark hold`.

**Comment by dlech** [comment] 2015-01-23 17:52
My new bug got marked as a duplicate of [this bug](https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1387303). It looks the the problem has been fixed in vivid and they are working on getting it backported to utopic and trusty.

**Comment by dlech** [comment] 2015-01-29 02:01
In case anyone is not following the Ubuntu bug reports, the fix has been released in trusty-proposed (and utopic proposed).

You an also downloaded directly (for trusty amd64):
https://launchpad.net/ubuntu/trusty/amd64/gnome-keyring/3.10.1-1ubuntu4.2

**Comment by taurus-forever** [comment] 2015-02-23 09:42
JFYI, Confirmed the fix of my issue "Cannot connect to socket ..." by gnome-keyring  3.10.1-1ubuntu4.2 
Thank you!

**Closed** 2015-03-21 23:19 UTC
Labels: docs needed
