### ISSUE TITLE
Error while loading key from entry

### ISSUE THREAD

**Issue by pentium10** [dlech/KeeAgent#121] opened 2015-09-24 07:44 UTC
![image](https://cloud.githubusercontent.com/assets/465691/10067962/409532fa-62a9-11e5-9bd7-36e4b80fa8db.png)

using the latest Beta v0.7.6

**Comment by dlech** [comment] 2015-09-24 14:51
Can you please tell me more about your ssh key. Are you using .ppk format or open ssh? Is it RSA, DSA, etc.? Can you create a new key and reproduce the problem?

I also see that you are running in Client Mode. Is Pageant running?

**Comment by pentium10** [comment] 2015-09-24 15:14
so I am using PPK, RSA-1024. Pageant did run, I also upgraded them today, and still had the issue. But after a system restart it went away.

**Comment by dlech** [comment] 2015-09-24 15:25
I'm going to close the issue since it seems to be working. If it happens again, we can re-open.

**Closed by dlech** 2015-09-24 15:25 UTC
