### ISSUE TITLE
Unlock databases on request, but only if no key are loaded

### ISSUE THREAD

**Issue by mehrdadn** [dlech/KeeAgent#212] opened 2018-02-27 01:45 UTC
(edit: sorry, this was a duplicate of #179)

**Comment by dlech** [comment] 2018-02-27 02:09
Sounds like a duplicate of #179 perhaps?

**Comment by mehrdadn** [comment] 2018-02-27 02:10
Ahh whoops, my own post! I forgot I'd reported this, thanks!

**Closed** 2018-02-27 02:10 UTC
