### ISSUE TITLE
KeeAgent v0.11.1 does not work with mono 

### ISSUE THREAD

**Issue by jnko** [dlech/KeeAgent#284] opened 2019-10-16 09:25 UTC
Trying to run Keepass 2.4.3 with KeeAgent 0.11.1 running on Linux (Arch) with mono 6.0.0 or 6.4.0 fails.

```
The plugin cannot be loaded.
A newer .NET Framework is required.
```

Running Mono 6.0.0 or 6.4.0
```
mono -V
Mono JIT compiler version 6.0.0 (makepkg/6256b82d62f Fri 20 Sep 2019 11:18:59 PM -03)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

```
Mono JIT compiler version 6.4.0 (makepkg/fe64a4765e6 Wed 16 Oct 2019 12:40:59 PM CEST)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

Any idea how to solve this? (Edit: beside upgrading mono to6 6.4.0)

Thanks in advance

**Comment by dlech** [comment] 2019-10-16 19:43
duplicate of #271

**Closed by dlech** 2019-10-16 19:43 UTC
Labels: duplicate
