### ISSUE TITLE
KeeAgent not starting on Linux

### ISSUE THREAD

**Issue by pahofmann** [dlech/KeeAgent#123] opened 2015-10-25 16:16 UTC
I get the following error when compilation is finished after the starting keepass:
```
 KeeAgent failed to load:
 Failed to start Unix Agent: Object reference not set to instance of an object
```
Any ideas whats causing this?

**Comment by dlech** [comment] 2015-10-25 18:34
I have just added Agent mode support for Linux, so you have found a bug with this. Unfortunate, this is not enough information to find out exactly what the problem is, but I will try a clean install and see if I can reproduce the error.

To get your KeePass working again, you will probably have to manually edit your KeePass.config.xml file to set it to client mode. On Linux, this file is usually found at `~/.config/KeePass/` (or possibly in the same folder as `KeePass.exe`. Open it in a text editor and look for "KeeAgent.AgentMode":

		<Item>
			<Key>KeeAgent.AgentMode</Key>
			<Value>Auto</Value>
		</Item>


change the Value to "Client"

    <Value>Client</Value>

KeePass/KeeAgent should work as before.

**Comment by pahofmann** [comment] 2015-10-25 19:53
I've edited the line now I get the following error when unlocking my database:
```
KeeAgent: Error while loading key from entry xxxxxxx
Could not add key because no SSh agent was found.
Please make sure your SSH agent is running (e.g. pagent)
```
Is there something else I need to configure to get it working with OpenSSH?

If I can provide Debug information to help just let me know what you need.

**Comment by dlech** [comment] 2015-10-25 20:08
Was this working before? Do you have `ssh-agent` running? (you can test this by running `ssh-add -l` in a terminal).

**Comment by pahofmann** [comment] 2015-10-25 20:12
No havent used it before under linux, so it wasnt working before.`
`ssh-agent`  is running but `ssh-add` states `Could not open a connection to your authentication agent.` so there seems to be a problem with the agent.

**Comment by dlech** [comment] 2015-10-25 20:38
Did you start `ssh-agent` manually? It needs to be started by your session manager so that it can be seen by all processes. What is `echo $SSH_AUTH_SOCK`? I'm gessing not anything since `ssh-add` didn't work.

What Linux distro and desktop environment are you using?

**Comment by pahofmann** [comment] 2015-10-25 20:52
I'm using gnome on archlinux.
I disabled the ssh-component of the gnome-keyring as mentioned in the first step of the installation page. That seems to have caused the issue. After reverting the changes ssh-agent is starting normal and everything works fine.

**Comment by dlech** [comment] 2015-11-02 22:36
This is fixed in v0.7.9.

**Closed by dlech** 2015-11-02 22:36 UTC
Labels: bug
