### ISSUE TITLE
Windows 10 Agent mode KeePass freeze

### ISSUE THREAD

**Issue by schklom** [dlech/KeeAgent#337] opened 2022-01-27 22:42 UTC
Hello, I think I have a bug.

Note that I could be doing something wrong since no one else seems to have the same issue as me.

## Config KeeAgent

* Agent mode: Client
* Option `Enable agent for Windows OpenSSH (experimental)` enabled (otherwise, a loaded key cannot be used by `ssh`. Disabling this does not solve the problem)
* An entry with a passphrase protected private key (type ED25519, size 256, passphrase 64 characters)
* No key is loaded.

## Config Windows 10

* Service `OpenSSH Authentication Agent` is disabled.
* Opening `Pageant` gives me the message `Pageant is already running`. Should I stop it?

## Problem

* Check `Allow KeeAgent to use this entry` in the entry
* Pick the private key file
* Click `OK`
* Close entry
* Open other entry/folder or simply select another entry
* KeePass freezes (becomes unresponsive) for 5-10 seconds while using around 17% CPU

## Noteworthy

The private key can be loaded manually from file into KeeAgent (without relying on the KeePass entry) and works with the command line `ssh`.

When loaded from KeePass entry, the private key does not work with the command line `ssh`

## Question

Does anyone have any idea what is going on?

Many thanks :)

**Comment by dlech** [comment] 2022-01-29 02:50
Can you generate a new key that causes this problem and attach it to the issue (email attachments don't work - put it in a .zip and use the web interface to attach to a new comment).

**Comment by dlech** [comment] 2022-01-29 02:52
I have a feeling that the problem is that new private key encryption is intentionally CPU intensive and some mechanism in KeePass is triggering a read of the public key hash which requires decrypting the key.

**Comment by schklom** [comment] 2022-01-29 03:44
@dlech This one causes the same issue and I don't use it: [test.zip](https://github.com/dlech/KeeAgent/files/7962886/test.zip)
Its passphrase is `8D9C02B767356573C8CB68CED55CA4A076CBEED0F95CE1CE1D1D00BD9B2403E6` (64 characters)
I generated it with `ssh-keygen -t ed25519 -a 250 -f test`

Having a shorter passphrase (26 characters) provokes less freezes and they last a shorter time, but it is still too much especially since I plan to have more than one key loaded.

I wouldn't mind if the CPU intensive operations happen when I use the key, but they go on whenever I do anything on KeePass. Should I make an issue on the KeePass repo, or is this a KeeAgent problem?

**Comment by dlech** [comment] 2022-01-29 03:53
Thanks. I can confirm seeing the delay. I will look into it more later.

**Comment by schklom** [comment] 2022-01-29 03:57
@dlech Thanks :)

**Comment by dlech** [comment] 2022-01-29 23:33
This is probably the same problem as #243.

**Comment by schklom** [comment] 2022-01-30 00:06
I hadn't seen that issue, oops.

I agree it is likely the same problem.
I'll monitor that issue and close this one when it gets fixed in case it is not the same problem.

**Comment by dlech** [comment] 2022-07-17 23:13
should be fixed in https://github.com/dlech/KeeAgent/releases/tag/v0.13.1

**Closed by dlech** 2022-07-17 23:13 UTC
Labels: bug
